### ISSUE TITLE
Steph's to-do list from ISBI admin mtg 22 Feb 2021

### ISSUE THREAD

**Issue by skbowd** [isudatateam/datateam#358]
@loriabendroth @lnowatzke  See notes below.

- [x] Check partnership criteria to determine if it was listed as just a partnership or an event, meeting, etc. with a partner.
       _Note: Partnerships without an event are now pink under description.  This makes up about 50% of PB category. Laurie- let me know if you would like to differentiate the two somehow in the spreadsheet._
- [x] Add dimension to BHCCB as Soil and Water Conservation District NGO.
- [x] Delete IDALS partnerships.
       _Note: Instead of deleting, I added a keep/delete column to admin and marked these to delete._
- [x] Expanded entries within Outreach & Education with #s in parenthesis.  
       _Note:  I did not do this for social media entries._
- [x] Categorize DN_01 or DN_02 in blank cells for Extension & Outreach.
       _Note:  These were all from DN_01 as suspected.  I added text to DN_01 methods about brining in data from DN_02._
- [x] Determine number of months each Project Coordinator was employed by given watershed.
- [x] Determine number of quarters each watershed project was in operation.
