### ISSUE TITLE
Update meta sheets for SEPAC

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#360]
@skbowd , for SEPAC, move data out of "moved from NNK" folder into main SEPAC folder and update sheets as listed below.  
https://drive.google.com/drive/u/0/folders/15xOmzV91iDruz3dYn_VMXjJCWXG-MZWG 

- [x] Populate in all known data into 1. Site Information. Pull data in from spreadsheets that Eileen has sent as well as papers. 
- [x] Populate in all known data into 2. One-Time Plot Data. Pull data in from spreadsheets that Eileen has sent as well as papers. 
- [x] Populate in all known data into 3. Yearly Treatment Data. Pull data in from spreadsheets that Eileen has sent as well as papers. 
- [x] Remove non-applicable data types and add in others to the Data Dictionary. Only include data that will be contained within this published data set. 
- [x] I am not sure we need the Data Collected or Master Treatment spreadsheets since we will publish the Data Dictionary and Yearly Treatment Data. Review these data files and see if valuable; otherwise delete.

**Comment by skbowd** [comment]
@skbowd to do:
- [ ]  2. One-Time Plot Data. Need to expand once we have plot/rep data.
- [ ]  3. Yearly Treatment Data. Need to have each treatment replicated for plot numbers once we have plot/rep data.

@loriabendroth to do:
- [ ]  Data Dictionary. Pink text is information I entered.  Please review and add any information for TBD's I made as well.
- [ ]  Data Dictionary. Yellow highlighted rows for soil data are not currently headings in Soil Data- IN_SEPAC.  Should I add them?
- [ ]  Data Dictionary. Blue highlighted rows are for GHG data.  We do not currently have a spreadsheet on SEPAC google drive for GHG.  Should I create one?
- [ ]  I updated SEPAC Treatments (Master)- please review if you think we need to keep.  I would say no as all information is available elsewhere.
- [ ] I reviewed SEPAC Data Collected (Master)- It looks like the only plot data we have is for water.  I am not familiar enough with that type of data to know what exactly was collected. Not sure on value of keeping this file?
